import { ATRAC3PLUS_FRAME_SAMPLES } from "../constants.js";

export const AT5_SIGPROC_MAX_CHANNELS = 2;
export const AT5_SIGPROC_BANDS_MAX = 16;
export const AT5_SIGPROC_SLOTS = 9;
export const AT5_SIGPROC_SUBSAMPLES = 128;
export const AT5_SIGPROC_FRAME_SAMPLES = ATRAC3PLUS_FRAME_SAMPLES;
export const AT5_SIGPROC_TAIL_SAMPLES = 384;
export const AT5_SIGPROC_WINDOW_SAMPLES = AT5_SIGPROC_TAIL_SAMPLES + AT5_SIGPROC_FRAME_SAMPLES;
export const AT5_SIGPROC_CORR_SAMPLES = AT5_SIGPROC_SUBSAMPLES * 2;

export const AT5_SIGPROC_AUX_BYTES = 0x884;
export const AT5_SIGPROC_INTENSITY_DEFAULT = 0x10;
